version: 2
jobs:
  deploy:
    docker:
      - image: cimg/node:15.5.1
    steps:
      - checkout
      - run:
          name: check version
          command: node --version
      - run:
          name: npm install
          command: npm install
      - run:
          name: node/test
          command: npm run test

workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - staging
                - master
